{% set name = "rattler-build-conda-compat" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nichmor/rattler-build-conda-compat/releases/download/v{{ version }}/rattler-build-conda-compat-{{ version }}.tar.gz
  sha256: c6fa25d88d5e58ba51f094a4283dbf6eb7eed86ca4efb1495105e550ca93bc95
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=45
  run:
    - python >=3.8
    - rattler-build
    - conda-build
    - pytest
    

test:
  imports:
    - rattler_build_conda_compat.loader
    - rattler_build_conda_compat.render
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/nichmor/rattler-build-conda-compat
  summary: 'rattler-build module which offer compatibility with conda-smithy'
  description: |
    rattler-build module which offer compatibility with conda-smithy
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nichmor
