{% set name = "rattler-build-conda-compat" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prefix-dev/rattler-build-conda-compat/releases/download/v{{ version }}/rattler_build_conda_compat-{{ version }}.tar.gz
  sha256: 106b890b0feb4295d6409a7c8e6ce6bbf0a92a081c639c6eb144125edcd3a5b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.24.0
  run:
    - python >=3.8
    - rattler-build
    - conda-build
    - typing-extensions >=4.12.2,<5
    - tomli
    - ruamel.yaml
    - jinja2 >=3.0.2,<4
    - types-PyYAML >=6.0.12.20240311,<6.0.13

test:
  # Verify that the package can be succesfully imported
  imports:
    - rattler_build_conda_compat.loader
    - rattler_build_conda_compat.render
    - rattler_build_conda_compat.conditional_list
    - rattler_build_conda_compat.recipe_sources
  requires:
    - pip
    # Test against the lowest supported python version
    - python 3.8.*
    # test dependencies
    - pytest
    - syrupy
  commands:
    - pip check
    - pytest ./tests
  source_files:
    - tests/
  downstreams:
    - conda-smithy >=3.37.0

about:
  home: https://github.com/nichmor/rattler-build-conda-compat
  summary: 'rattler-build module which offer compatibility with conda-smithy'
  description: |
    rattler-build module which offer compatibility with conda-smithy
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - baszalmstra
    - nichmor
    - tdejager
