{% set name = "rattler-build-conda-compat" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nichmor/rattler-build-conda-compat/releases/download/v{{ version }}/rattler_build_conda_compat-{{ version }}.tar.gz
  sha256: d4da49ce71268c4f8b29f76c36e8317125ae291b84fcfb48c71b248f6ab9d236

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.24.0
  run:
    - python >=3.10
    - rattler-build
    - conda-build
    - typing-extensions >=4.12.2,<5
    - tomli
    - ruamel.yaml

test:
  # Verify that the package can be succesfully imported
  imports:
    - rattler_build_conda_compat.loader
    - rattler_build_conda_compat.render
    - rattler_build_conda_compat.conditional_list
    - rattler_build_conda_compat.recipe_sources
  requires:
    - pip
    # test dependencies
    - pytest
    - syrupy
  commands:
    - pip check
    - pytest ./tests
  source_files:
    - tests/
  downstreams:
    - conda-smithy >=3.37.0

about:
  home: https://github.com/nichmor/rattler-build-conda-compat
  summary: 'rattler-build module which offer compatibility with conda-smithy'
  description: |
    rattler-build module which offer compatibility with conda-smithy
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - baszalmstra
    - nichmor
    - tdejager
