# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: rattler-build-conda-compat
  version: "0.0.3"

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url: https://github.com/nichmor/rattler-build-conda-compat/releases/download/v${{ version }}/rattler_build_conda_compat-${{ version }}.tar.gz
  sha256: 18d3e6ea2aaf20d0c8ba1de6944f56a84ef935bcc465eb917a7ff789e59e3018

build:
  number: 0
  noarch: python
  script:
    - python -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=45
  run:
    - python >=3.8
    - rattler-build
    - conda-build
    - pytest

tests:
  - python:
      imports:
        - rattler_build_conda_compat.loader
        - rattler_build_conda_compat.render


about:
  homepage: https://github.com/nichmor/rattler-build-conda-compat
  summary: rattler-build module which offer compatibility with conda-smithy
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nichmor
